site_name: Sueleti - Mis notas
nav:
  - Inicio: 'index.md'
  - Linux: 'linux.md'
  - MkDocs: 'mkdocsSyntax.md'

markdown_extensions:
  - admonition
  - toc
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_png

theme:
  name: 'material'