site_name: My Docs
nav:
  - Inicio: 'index.md'
  - Comandos Linux: 'linux.md'
  - MkDocs: 'mkdocsSyntax.md'

markdown_extensions:
  - admonition
  - toc
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png